sudo: false
language: node_js
node_js:
  - '8'
install:
  - npm i npminstall && npminstall
os:
  - osx
  - linux
script:
  - DEBUG=egg-ts-helper* npm run cov
after_script: "npm install coveralls && cat ./coverage/lcov.info | coveralls"
